[build]
command = "npm run build"
publish = "dist"

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "https://esviji.netlify.app"
  to = "https://play.esviji.com"
  status = 301
  force = true
